[2021-01-11 18:27:04,826] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: MarketVol.apple_price_analyzer 2021-01-12T02:26:54.057549+00:00 [queued]>
[2021-01-11 18:27:04,832] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: MarketVol.apple_price_analyzer 2021-01-12T02:26:54.057549+00:00 [queued]>
[2021-01-11 18:27:04,832] {taskinstance.py:1017} INFO - 
--------------------------------------------------------------------------------
[2021-01-11 18:27:04,832] {taskinstance.py:1018} INFO - Starting attempt 1 of 1
[2021-01-11 18:27:04,832] {taskinstance.py:1019} INFO - 
--------------------------------------------------------------------------------
[2021-01-11 18:27:04,837] {taskinstance.py:1038} INFO - Executing <Task(BashOperator): apple_price_analyzer> on 2021-01-12T02:26:54.057549+00:00
[2021-01-11 18:27:04,840] {standard_task_runner.py:51} INFO - Started process 56211 to run task
[2021-01-11 18:27:04,846] {standard_task_runner.py:75} INFO - Running: ['airflow', 'tasks', 'run', 'MarketVol', 'apple_price_analyzer', '2021-01-12T02:26:54.057549+00:00', '--job-id', '31', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/stock_dags.py', '--cfg-path', '/var/folders/hy/5f75_vt15hb_bfkv9vvnx5sw0000gn/T/tmp79x0n2pq']
[2021-01-11 18:27:04,847] {standard_task_runner.py:76} INFO - Job 31: Subtask apple_price_analyzer
[2021-01-11 18:27:04,879] {logging_mixin.py:103} INFO - Running <TaskInstance: MarketVol.apple_price_analyzer 2021-01-12T02:26:54.057549+00:00 [running]> on host 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2021-01-11 18:27:04,900] {taskinstance.py:1232} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=MarketVol
AIRFLOW_CTX_TASK_ID=apple_price_analyzer
AIRFLOW_CTX_EXECUTION_DATE=2021-01-12T02:26:54.057549+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-01-12T02:26:54.057549+00:00
[2021-01-11 18:27:04,901] {bash.py:135} INFO - Tmp dir root location: 
 /var/folders/hy/5f75_vt15hb_bfkv9vvnx5sw0000gn/T
[2021-01-11 18:27:04,902] {bash.py:158} INFO - Running command: python /Users/chowli/Documents/Springboard_DE/Projects/mini-projects/Airflow/marketvol/airflow/script/analyze.py --symbol AAPL
[2021-01-11 18:27:04,908] {bash.py:169} INFO - Output:
[2021-01-11 18:27:05,339] {bash.py:173} INFO - /private/var/folders/hy/5f75_vt15hb_bfkv9vvnx5sw0000gn/T/airflowtmp8xh3itrh/tmp/data/2021-01-11
[2021-01-11 18:27:05,341] {bash.py:173} INFO - Traceback (most recent call last):
[2021-01-11 18:27:05,341] {bash.py:173} INFO -   File "/Users/chowli/Documents/Springboard_DE/Projects/mini-projects/Airflow/marketvol/airflow/script/analyze.py", line 35, in <module>
[2021-01-11 18:27:05,342] {bash.py:173} INFO -     main()
[2021-01-11 18:27:05,342] {bash.py:173} INFO -   File "/Users/chowli/Documents/Springboard_DE/Projects/mini-projects/Airflow/marketvol/airflow/script/analyze.py", line 31, in main
[2021-01-11 18:27:05,342] {bash.py:173} INFO -     read_data(symbol)
[2021-01-11 18:27:05,343] {bash.py:173} INFO -   File "/Users/chowli/Documents/Springboard_DE/Projects/mini-projects/Airflow/marketvol/airflow/script/analyze.py", line 24, in read_data
[2021-01-11 18:27:05,343] {bash.py:173} INFO -     df = pd.read_csv(file)
[2021-01-11 18:27:05,343] {bash.py:173} INFO -   File "/Users/chowli/.local/share/virtualenvs/marketvol-WbDfdy4N/lib/python3.7/site-packages/pandas/io/parsers.py", line 605, in read_csv
[2021-01-11 18:27:05,343] {bash.py:173} INFO -     return _read(filepath_or_buffer, kwds)
[2021-01-11 18:27:05,344] {bash.py:173} INFO -   File "/Users/chowli/.local/share/virtualenvs/marketvol-WbDfdy4N/lib/python3.7/site-packages/pandas/io/parsers.py", line 457, in _read
[2021-01-11 18:27:05,344] {bash.py:173} INFO -     parser = TextFileReader(filepath_or_buffer, **kwds)
[2021-01-11 18:27:05,344] {bash.py:173} INFO -   File "/Users/chowli/.local/share/virtualenvs/marketvol-WbDfdy4N/lib/python3.7/site-packages/pandas/io/parsers.py", line 814, in __init__
[2021-01-11 18:27:05,344] {bash.py:173} INFO -     self._engine = self._make_engine(self.engine)
[2021-01-11 18:27:05,345] {bash.py:173} INFO -   File "/Users/chowli/.local/share/virtualenvs/marketvol-WbDfdy4N/lib/python3.7/site-packages/pandas/io/parsers.py", line 1045, in _make_engine
[2021-01-11 18:27:05,345] {bash.py:173} INFO -     return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
[2021-01-11 18:27:05,345] {bash.py:173} INFO -   File "/Users/chowli/.local/share/virtualenvs/marketvol-WbDfdy4N/lib/python3.7/site-packages/pandas/io/parsers.py", line 1862, in __init__
[2021-01-11 18:27:05,346] {bash.py:173} INFO -     self._open_handles(src, kwds)
[2021-01-11 18:27:05,346] {bash.py:173} INFO -   File "/Users/chowli/.local/share/virtualenvs/marketvol-WbDfdy4N/lib/python3.7/site-packages/pandas/io/parsers.py", line 1363, in _open_handles
[2021-01-11 18:27:05,346] {bash.py:173} INFO -     storage_options=kwds.get("storage_options", None),
[2021-01-11 18:27:05,347] {bash.py:173} INFO -   File "/Users/chowli/.local/share/virtualenvs/marketvol-WbDfdy4N/lib/python3.7/site-packages/pandas/io/common.py", line 644, in get_handle
[2021-01-11 18:27:05,347] {bash.py:173} INFO -     newline="",
[2021-01-11 18:27:05,347] {bash.py:173} INFO - FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/hy/5f75_vt15hb_bfkv9vvnx5sw0000gn/T/airflowtmp8xh3itrh/tmp/data/2021-01-11/AAPL.csv'
[2021-01-11 18:27:05,387] {bash.py:177} INFO - Command exited with return code 1
[2021-01-11 18:27:05,394] {taskinstance.py:1396} ERROR - Bash command failed. The command returned a non-zero exit code.
Traceback (most recent call last):
  File "/Users/chowli/.local/share/virtualenvs/marketvol-WbDfdy4N/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1086, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/Users/chowli/.local/share/virtualenvs/marketvol-WbDfdy4N/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1260, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/Users/chowli/.local/share/virtualenvs/marketvol-WbDfdy4N/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1300, in _execute_task
    result = task_copy.execute(context=context)
  File "/Users/chowli/.local/share/virtualenvs/marketvol-WbDfdy4N/lib/python3.7/site-packages/airflow/operators/bash.py", line 180, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2021-01-11 18:27:05,397] {taskinstance.py:1440} INFO - Marking task as FAILED. dag_id=MarketVol, task_id=apple_price_analyzer, execution_date=20210112T022654, start_date=20210112T022704, end_date=20210112T022705
[2021-01-11 18:27:05,457] {local_task_job.py:118} INFO - Task exited with return code 1
