[2021-01-13 17:23:11,393] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: MarketVol.download_telsa_price 2021-01-13T18:00:00+00:00 [queued]>
[2021-01-13 17:23:11,398] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: MarketVol.download_telsa_price 2021-01-13T18:00:00+00:00 [queued]>
[2021-01-13 17:23:11,398] {taskinstance.py:1017} INFO - 
--------------------------------------------------------------------------------
[2021-01-13 17:23:11,398] {taskinstance.py:1018} INFO - Starting attempt 4 of 4
[2021-01-13 17:23:11,398] {taskinstance.py:1019} INFO - 
--------------------------------------------------------------------------------
[2021-01-13 17:23:11,405] {taskinstance.py:1038} INFO - Executing <Task(PythonOperator): download_telsa_price> on 2021-01-13T18:00:00+00:00
[2021-01-13 17:23:11,407] {standard_task_runner.py:51} INFO - Started process 5865 to run task
[2021-01-13 17:23:11,414] {standard_task_runner.py:75} INFO - Running: ['airflow', 'tasks', 'run', 'MarketVol', 'download_telsa_price', '2021-01-13T18:00:00+00:00', '--job-id', '112', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/stock_dags.py', '--cfg-path', '/var/folders/hy/5f75_vt15hb_bfkv9vvnx5sw0000gn/T/tmpac55noec']
[2021-01-13 17:23:11,415] {standard_task_runner.py:76} INFO - Job 112: Subtask download_telsa_price
[2021-01-13 17:23:11,449] {logging_mixin.py:103} INFO - Running <TaskInstance: MarketVol.download_telsa_price 2021-01-13T18:00:00+00:00 [running]> on host 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2021-01-13 17:23:11,472] {taskinstance.py:1232} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=MarketVol
AIRFLOW_CTX_TASK_ID=download_telsa_price
AIRFLOW_CTX_EXECUTION_DATE=2021-01-13T18:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-01-13T18:00:00+00:00
[2021-01-13 17:23:11,473] {logging_mixin.py:103} INFO - 2021-01-13
[2021-01-13 17:23:11,474] {logging_mixin.py:103} INFO - 2021-01-14
[2021-01-13 17:23:11,674] {logging_mixin.py:103} INFO - [*********************100%***********************]  1 of 1 completed
[2021-01-13 17:23:11,675] {logging_mixin.py:103} INFO - 
[2021-01-13 17:23:11,678] {taskinstance.py:1396} ERROR - [Errno 2] No such file or directory: '/Users/chowli/Documents/Springboard_DE/Projects/mini-projects/Airflow/marketvol/tmp/data/2021-01-13/TSLA.csv'
Traceback (most recent call last):
  File "/Users/chowli/.local/share/virtualenvs/marketvol-WbDfdy4N/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1086, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/Users/chowli/.local/share/virtualenvs/marketvol-WbDfdy4N/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1260, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/Users/chowli/.local/share/virtualenvs/marketvol-WbDfdy4N/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1300, in _execute_task
    result = task_copy.execute(context=context)
  File "/Users/chowli/.local/share/virtualenvs/marketvol-WbDfdy4N/lib/python3.7/site-packages/airflow/operators/python.py", line 117, in execute
    return_value = self.execute_callable()
  File "/Users/chowli/.local/share/virtualenvs/marketvol-WbDfdy4N/lib/python3.7/site-packages/airflow/operators/python.py", line 128, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/chowli/Documents/Springboard_DE/Projects/mini-projects/Airflow/marketvol/airflow/dags/stock_dags.py", line 32, in fetch_price
    "{}/tmp/data/{}/{}.csv".format(os.getcwd(), start_date, kwargs['ticker']))
  File "/Users/chowli/.local/share/virtualenvs/marketvol-WbDfdy4N/lib/python3.7/site-packages/pandas/core/generic.py", line 3400, in to_csv
    storage_options=storage_options,
  File "/Users/chowli/.local/share/virtualenvs/marketvol-WbDfdy4N/lib/python3.7/site-packages/pandas/io/formats/format.py", line 1083, in to_csv
    csv_formatter.save()
  File "/Users/chowli/.local/share/virtualenvs/marketvol-WbDfdy4N/lib/python3.7/site-packages/pandas/io/formats/csvs.py", line 234, in save
    storage_options=self.storage_options,
  File "/Users/chowli/.local/share/virtualenvs/marketvol-WbDfdy4N/lib/python3.7/site-packages/pandas/io/common.py", line 644, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/Users/chowli/Documents/Springboard_DE/Projects/mini-projects/Airflow/marketvol/tmp/data/2021-01-13/TSLA.csv'
[2021-01-13 17:23:11,684] {taskinstance.py:1440} INFO - Marking task as FAILED. dag_id=MarketVol, task_id=download_telsa_price, execution_date=20210113T180000, start_date=20210114T012311, end_date=20210114T012311
[2021-01-13 17:23:11,724] {local_task_job.py:118} INFO - Task exited with return code 1
